integration:
  name: minitest
includes:
- lib
requires:
- project_management
matcher:
  subjects:
  - ProjectManagement*
  ignore:
    - ProjectManagement::Test*
    - ProjectManagement::CommandHandler#load_issue
    - ProjectManagement::CommandHandler#create_issue
