source "https://rubygems.org"

gem "ruby_event_store"
gem "minitest"
gem "mutant"
gem "mutant-minitest"
gem "mutant-license",
    source: "https://oss:7AXfeZdAfCqL1PvHm2nvDJO6Zd9UW8IK@gem.mutant.dev"
gem "activerecord"
gem "sqlite3", "< 2"
gem "aasm"
