integration:
  name: minitest
includes:
  - lib
requires:
  - project_management
matcher:
  subjects:
    - ProjectManagement*
  ignore:
    - ProjectManagement::Test*
    - ProjectManagement::Issue#open
    - ProjectManagement::Open*
    - ProjectManagement::InProgress*
    - ProjectManagement::Resolved*
    - ProjectManagement::Closed*
coverage_criteria:
  process_abort: true
usage: opensource