integration:
  name: minitest
includes:
- lib
requires:
- project_management
matcher:
  subjects:
  - ProjectManagement*
  ignore:
  - ProjectManagement::Issue#open
  - ProjectManagement::Open*
  - ProjectManagement::InProgress*
  - ProjectManagement::Resolved*
  - ProjectManagement::Closed*
