integration:
  name: minitest
includes:
  - lib
requires:
  - project_management
matcher:
  subjects:
    - ProjectManagement*
  ignore:
    - ProjectManagement::Issue#apply_on_state
    - ProjectManagement::Issue#apply
    - ProjectManagement::Test*
    - ProjectManagement::Issue::Repository*
    - ProjectManagement::CommandHandler#with_aggregate

