require_relative '../lib/project_management'
require_relative 'aggregate_root'
require_relative 'aggregate_repository'
require_relative 'project_management/command_handler'
require_relative 'project_management/issue'
